apiVersion: apps/v1
kind: Deployment
metadata:
  name: demomicro
spec:
  selector:
    matchLabels:
      app: demomicro
  replicas: 2
  template:
    metadata:
      labels:
        app: demomicro
    spec:
      containers:
        - name: demomicro
          image: docker.io/library/demomicro:0.0.1-SNAPSHOT
          imagePullPolicy: Always
          ports:
            - containerPort: 8080