apiVersion: apps/v1
kind: Deployment
metadata:
  name: demomicro
  namespace: demomicro
  labels:
    app: demomicro-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demomicro-app
  template:
    metadata:
      labels:
        app: demomicro-app
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: demomicro
          image: rasty2/demomicro:0.0.1-SNAPSHOT
          imagePullPolicy: Always
          ports:
            - containerPort: 8080