name: Deploy to ECR

on:
  push:
    branches: [ main ]

env:
  ECR_REPOSITORY:demomicro

jobs:

  build:

    name: Build Image
    runs-on: ubuntu-latest


    steps:

      - name: Check out code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Build and tag Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ vars.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:latest

      - name: Get the Docker image digest
        id: get-image-digest
        run: echo "::set-output name=digest::$(docker inspect --format='{{index .RepoDigests 0}}' ${{ vars.ECR_REGISTRY }}/$ECR_REPOSITORY:latest)"

      - name: Store Docker image digest
        id: store-image-digest
        run: echo "DOCKER_IMAGE_DIGEST=${{ steps.image-digest.outputs.digest }}" >> $GITHUB_ENV